[tool.poetry]
name = "code-in-place"
version = "0.1.0"
description = ""
authors = ["Joseph Lee <jlee7x2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
beautifulsoup4 = "^4.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
